{% set name = "eigenpy" %}
{% set version = "3.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stack-of-tasks/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: c88df6b44ccf8ac4cddc4c1015a3f1c3cbd7425cac1342f07ac16bc6f2b33f87

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - clang  # [win]
    - make  # [not win]
    - ninja  # [win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - eigen
    - libboost-python-devel
    - numpy
    - python
    - scipy
  run:
    - eigen
    - libboost-python-devel
    - python
    - scipy

test:
  requires:
    - pkg-config
    - libboost-python-devel
  imports:
    - eigenpy
  commands:
    - pkg-config --modversion eigenpy

about:
  home: http://github.com/stack-of-tasks/eigenpy
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Bindings between Numpy and Eigen using Boost.Python
  dev_url: https://github.com/stack-of-tasks/eigenpy

extra:
  recipe-maintainers:
    - jorisv
    - jcarpent
    - wolfv
    - seanyen
