{% set name = "eigenpy" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stack-of-tasks/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: b53d6a45fd8d9ec996723d8b43d1cfc312e71636ceee54cec228ddf2998e2921

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}  # [not win]
    - vs2017_win-64  # [win64]
    - vs2017_win-32  # [win32]
    - cmake
    - make  # [not win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - eigen
    - boost
    - numpy
    - python
  run:
    - eigen
    - boost
    - {{ pin_compatible('numpy') }}
    - python

test:
  requires:
    - pkg-config
    - boost
  imports:
    - eigenpy
  commands:
    - pkg-config --modversion eigenpy

about:
  home: http://github.com/stack-of-tasks/eigenpy
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING.LESSER
  summary: Bindings between Numpy and Eigen using Boost.Python
  dev_url: https://github.com/stack-of-tasks/eigenpy

extra:
  recipe-maintainers:
    - jcarpent
    - wolfv
    - seanyen
