{% set name = "eigenpy" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stack-of-tasks/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad619bda7c24a129ce5469de7dc4544220c31db1fce5d0a37ceb64824cfa8978

  patches:
    # Deactivate unique_ptr test in C++11
    - patches/0001-cmake-Don-t-build-std_unique_ptr-unit-tests-if-CMAKE.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake
    - clang  # [win]
    - make  # [not win]
    - ninja  # [win]
  host:
    - eigen
    - libboost-python-devel
    - numpy
    - python
    - scipy
  run:
    - eigen
    - libboost-python-devel
    - {{ pin_compatible('numpy') }}
    - python
    - scipy

test:
  requires:
    - pkg-config
    - libboost-python-devel
  imports:
    - eigenpy
  commands:
    - pkg-config --modversion eigenpy

about:
  home: http://github.com/stack-of-tasks/eigenpy
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Bindings between Numpy and Eigen using Boost.Python
  dev_url: https://github.com/stack-of-tasks/eigenpy

extra:
  recipe-maintainers:
    - jorisv
    - jcarpent
    - wolfv
    - seanyen
