{% set name = "eigenpy" %}
{% set version = "1.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stack-of-tasks/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: cd5ebad1142c58748897c9eb3dc4bd8a7069f76cd2ac51093b1800019bace961

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}  # [not win]
    - vs2017_win-64  # [win64]
    - vs2017_win-32  # [win32]
    - cmake
    - make  # [not win]
    - pkg-config
  host:
    - eigen
    - boost
    - python
    - numpy
  run:
    - boost
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pkg-config
  imports:
    - eigenpy
  commands:
    - pkg-config --modversion eigenpy

about:
  home: http://github.com/stack-of-tasks/eigenpy
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING.LESSER
  summary: 'Bindings between Numpy and Eigen using Boost.Python'
  dev_url: https://github.com/stack-of-tasks/eigenpy

extra:
  recipe-maintainers:
    - jcarpent
    - wolfv
    - lesteve
    - seanyen
